import type { GeneratorOptions } from "./options";
import type { GeneratedModule } from "./string-emitter";

export function generateHelpersFile(
  options: GeneratorOptions,
): GeneratedModule {
  const jsLines = [
    '"use strict";',
    'Object.defineProperty(exports, "__esModule", { value: true });',
    "exports.transformInfoIntoPrismaArgs = transformInfoIntoPrismaArgs;",
    "exports.getPrismaFromContext = getPrismaFromContext;",
    "exports.transformCountFieldIntoSelectRelationsCount = transformCountFieldIntoSelectRelationsCount;",
    'const tslib_1 = require("tslib");',
    'const graphql_fields_1 = tslib_1.__importDefault(require("graphql-fields"));',
    "function transformInfoIntoPrismaArgs(info) {",
    "    const fields = (0, graphql_fields_1.default)(info, {}, {",
    '        excludedFields: ["__typename"],',
    "        processArguments: true,",
    "    });",
    "    return transformFields(fields);",
    "}",
    "function transformFields(fields) {",
    "    return Object.fromEntries(",
    "        Object.entries(fields).map(([key, value]) => {",
    "            if (Object.keys(value).length === 0) {",
    "                return [key, true];",
    "            }",
    '            if ("__arguments" in value) {',
    "                return [key, Object.fromEntries(",
    "                    value.__arguments.map(argument => {",
    "                        const [[argumentKey, { value: argumentValue }]] = Object.entries(argument);",
    "                        return [argumentKey, argumentValue];",
    "                    }),",
    "                )];",
    "            }",
    "            return [key, transformFields(value)];",
    "        }),",
    "    );",
    "}",
    "function getPrismaFromContext(context) {",
    `    const prismaClient = context[${JSON.stringify(options.contextPrismaKey)}];`,
    "    if (!prismaClient) {",
    `        throw new Error(${JSON.stringify(`Unable to find Prisma Client in GraphQL context. Please provide it under the \`context[\\"${options.contextPrismaKey}\\"]\` key.`)});`,
    "    }",
    "    return prismaClient;",
    "}",
    "function transformCountFieldIntoSelectRelationsCount(_count) {",
    "    return {",
    "        include: {",
    "            _count: {",
    "                select: {",
    "                    ...Object.fromEntries(Object.entries(_count).filter(([_, value]) => value != null)),",
    "                },",
    "            },",
    "        },",
    "    };",
    "}",
  ];

  const dtsLines = [
    'import type { GraphQLResolveInfo } from "graphql";',
    "export declare function transformInfoIntoPrismaArgs(info: GraphQLResolveInfo): Record<string, any>;",
    "export declare function getPrismaFromContext(context: any): any;",
    "export declare function transformCountFieldIntoSelectRelationsCount(_count: object): {",
    "    include: {",
    "        _count: {",
    "            select: Record<string, unknown>;",
    "        };",
    "    };",
    "};",
  ];

  return {
    js: `${jsLines.join("\n")}\n`,
    dts: `${dtsLines.join("\n")}\n`,
  };
}
